/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.util.Scanner;
import util.ClearScreen;

public class App {
    public static void main(String[] args) {
        new TitleScreen();

        Game game = new Game();
        while (true) {
            game.showGamePanel();
        }
    }

    
}
